import { DEFAULT_ROLES } from '@constant/common';
import {
  LIST_PERMISSION_USER_PERMISSION,
  SEARCH_PERMISSION_USER_PERMISSION,
  SET_PERMISSION_USER_PERMISSION,
} from '@utils/permissions/permission-setting';
import {
  LIST_POSITION_PERMISSION,
  SEARCH_POSITION_PERMISSION,
  SYNCHRONIZE_POSITION_PERMISSION,
} from '@utils/permissions/position';
import {
  CHANGE_PASSWORD_USER_PERMISSION,
  CREATE_USER_PERMISSION,
  DELETE_USER_PERMISSION,
  DETAIL_USER_PERMISSION,
  EXPORT_USER_PERMISSION,
  IMPORT_USER_PERMISSION,
  LIST_USER_PERMISSION,
  SEARCH_USER_PERMISSION,
  UPDATE_USER_PERMISSION,
} from '@utils/permissions/user';
import {
  CHANGE_STATUS_USER_ROLE_SETTING_PERMISSION,
  CREATE_USER_ROLE_SETTING_PERMISSION,
  DELETE_USER_ROLE_SETTING_PERMISSION,
  DETAIL_USER_ROLE_SETTING_PERMISSION,
  EXPORT_USER_ROLE_SETTING_PERMISSION,
  IMPORT_USER_ROLE_SETTING_PERMISSION,
  LIST_USER_ROLE_SETTING_PERMISSION,
  SEARCH_USER_ROLE_SETTING_PERMISSION,
  UPDATE_USER_ROLE_SETTING_PERMISSION,
} from '@utils/permissions/user-role-setting';

export const USER_RULE_CONST = {
  CODE: {
    MAX_LENGTH: 20,
  },
  USER_NAME: {
    MAX_LENGTH: 255,
  },
  FULL_NAME: {
    MAX_LENGTH: 255,
  },
  EMAIL: {
    MAX_LENGTH: 100,
  },
  PASSWORD: {
    MAX_LENGTH: 255,
    MIN_LENGTH: 6,
  },
  DATE_OF_BIRTH: {
    MAX_LENGTH: 255,
  },
  PHONE: {
    MIN_LENGTH: 10,
    MAX_LENGTH: 20,
  },
  STATUS: {
    MAX_LENGTH: 50,
  },
};

export enum StatusUserEnum {
  INACTIVE = 0,
  ACTIVE = 1,
}

export const USER_ROLE_SETTING_CONSTANT = {
  ADMIN: '01',
  LEADER: '02',
  MEMBER: '03',
};

export const DEPARTMENT_SETTING_CONSTANT = {
  ADMIN: '030600ADM',
  ME: 'ME',
  OTHER: 'OTHER',
};

export const USER_ROLE_DEFAULT = [
  {
    roldId: DEFAULT_ROLES[0].id, // LGA
    listPers: [
      // position
      LIST_POSITION_PERMISSION.code,
      SEARCH_POSITION_PERMISSION.code,
      SYNCHRONIZE_POSITION_PERMISSION.code,
    ],
  },
  {
    roldId: DEFAULT_ROLES[1].id, // Unit admin
    listPers: [
      // position
      LIST_POSITION_PERMISSION.code,
      SEARCH_POSITION_PERMISSION.code,
    ],
  },
  {
    roldId: DEFAULT_ROLES[2].id,
    listPers: [
      // position
      LIST_POSITION_PERMISSION.code,
      SEARCH_POSITION_PERMISSION.code,
      // user-role
      CREATE_USER_ROLE_SETTING_PERMISSION.code,
      UPDATE_USER_ROLE_SETTING_PERMISSION.code,
      DELETE_USER_ROLE_SETTING_PERMISSION.code,
      DETAIL_USER_ROLE_SETTING_PERMISSION.code,
      LIST_USER_ROLE_SETTING_PERMISSION.code,
      SEARCH_USER_ROLE_SETTING_PERMISSION.code,
      IMPORT_USER_ROLE_SETTING_PERMISSION.code,
      EXPORT_USER_ROLE_SETTING_PERMISSION.code,
      CHANGE_STATUS_USER_ROLE_SETTING_PERMISSION.code,
      // permission
      SET_PERMISSION_USER_PERMISSION.code,
      LIST_PERMISSION_USER_PERMISSION.code,
      SEARCH_PERMISSION_USER_PERMISSION.code,
      // users
      CREATE_USER_PERMISSION.code,
      UPDATE_USER_PERMISSION.code,
      DELETE_USER_PERMISSION.code,
      DETAIL_USER_PERMISSION.code,
      LIST_USER_PERMISSION.code,
      SEARCH_USER_PERMISSION.code,
      IMPORT_USER_PERMISSION.code,
      EXPORT_USER_PERMISSION.code,
      CHANGE_PASSWORD_USER_PERMISSION.code,
    ],
  }
];
