
import {
  PERMISSION_USER_GROUP_PERMISSION,
  PERMISSION_USER_PERMISSION,
} from './permission-setting';
import { SYSTEM_CONFIG_GROUP_PERMISSION, SYSTEM_CONFIG_PERMISSION } from './system-config';
import { USER_GROUP_PERMISSION, USER_PERMISSION } from './user';
import {
  USER_ROLE_SETTIING_PERMISSION,
  USER_ROLE_SETTING_GROUP_PERMISSION,
} from './user-role-setting';

export const PERMISSION = [
  USER_PERMISSION,
  PERMISSION_USER_PERMISSION,
  USER_ROLE_SETTIING_PERMISSION,
  SYSTEM_CONFIG_PERMISSION
].flatMap((e) => e);

export const GROUP_PERMISSION = [
  USER_GROUP_PERMISSION,
  PERMISSION_USER_GROUP_PERMISSION,
  USER_ROLE_SETTING_GROUP_PERMISSION,
  SYSTEM_CONFIG_GROUP_PERMISSION
];

export const INSERT_PERMISSION = {
  permission: PERMISSION,
  groupPermission: GROUP_PERMISSION,
};
